spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Jooqs
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: "classpath:db/migration"

flyway:
  enabled: true